
:spring-boot-ref-guide: http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/
:spring-boot-ref-guide-executable-jar: http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#getting-started-first-application-executable-jar


=== Build Application:
 $ mvn package

Copy the file {project-artifact-name}.jar anywhere on the server.
The JAR already contains the configuration for all available environments.
For further information please visit the  {spring-boot-ref-guide}[Spring Boot Reference Guide]

=== Start Application
==== Default Profile
Start application on command line. The _default_ profile supports a H2 datbase.
For more information please visit the {spring-boot-ref-guide-executable-jar}[Spring Boot Reference Guide] for further information.

    $ java -jar leaf-app.jar

There are additional Spring profiles available.

==== Development Profile
The _dev_ profile supports a PostgreSQL database.

 $ java -jar -Dspring.profiles.active=local leaf-app.jar

==== Profiles
.Table -Dspring.profiles.active=
|===
|Profile | Database

|dev
|h2

|local
|postgreSql
|===
