CREATE TABLE product (
  id integer generated BY DEFAULT AS IDENTITY,
  description varchar(30),
  image_url varchar(255),
  price decimal(19,2) not null,
  product_id varchar(30),
  version integer,
  primary key (id)
);


INSERT INTO product
  (description,
  image_url,
  price,
  product_id)
VALUES
  ('Spring Framework Guru Shirt',
  'https://springframework.guru/wp-content/uploads/2015/04/spring_framework_guru_shirt-rf412049699c14ba5b68bb1c09182bfa2_8nax2_512.jpg',
  18.95,
  '2352688457110683099');

INSERT INTO product
  (description,
  image_url,
  price,
  product_id)
VALUES
  ('Spring Framework Guru Mug',
  'https://springframework.guru/wp-content/uploads/2015/04/spring_framework_guru_coffee_mug-r11e7694903c348e1a667dfd2f1474d95_x7j54_8byvr_512.jpg',
  11.95,
  '168639393495335947');