CREATE TABLE product (
  id integer generated BY DEFAULT AS IDENTITY,
  description varchar(30),
  image_url varchar(255),
  price decimal(19,2) not null,
  product_id varchar(30),
  version integer,
  primary key (id)
);
